#+title: Collab Onboarding
#+bibliography: mac_bibliography.bib
Document on how to get use to the tech stack and the Moby server.
* Server (moby)
** Install and setup tailscale
Download and install [[https://tailscale.com/][tailcale]]. This will give you direct access to the server.

*** Macos installation from download
#+begin_src shell
/Applications/Tailscale.app/Contents/MacOS/Tailscale up --authkey tskey-abcdef1432341818
#+end_src
You will receive a machine key that you can use to enter the network.

*** Installed using brew/apt/...
#+begin_src shell
tailscale up --authkey tskey-abcdef1432341818
#+end_src

** Select packages
- Clone my [[https://github.com/afermg/clouds/][clouds]] repository.
- Copy the =homes/llanos= folder as =homes/$USER=. It comes with basic tools.
- Add the packages you need in packages.nix, like [[https://github.com/afermg/clouds/blob/61c765a7e6ad36f62f3ae81e4009b26cf10a09c8/homes/llanos/packages.nix#L5-L10][this]] example, which you can find in one of two ways:
  - The Nix Packages search tool [[https://search.nixos.org/packages][here]]
  - If you already have a nix command line with =nix-search= installed you can run =nix-search -q <package-name>=.
  - You can look at some of my packages [[https://github.com/afermg/clouds/blob/61c765a7e6ad36f62f3ae81e4009b26cf10a09c8/homes/amunoz/packages.nix#L3-L84][here]].
- Make sure to configure your git name and email in this step, just like [[https://github.com/afermg/clouds/blob/61c765a7e6ad36f62f3ae81e4009b26cf10a09c8/homes/llanos/packages.nix#L11-L15][this]].

** Add user to Nix Home manager
This section ensures that the home manager system finds your files and generates your user.
- There are a couple of places left to edit to get your own user.
  - =machine/moby/default.nix=

** Day-to-day access
You can access it in multiple ways.
*** Jupyter notebook
This method requires =screen= both in remote and local computers.
*** Step 1: Open Jupyter notebook on Moby

#+begin_src shell
ssh $USER@moby
screen
cd project/folder
# envrc should start by itself here. If this project has not been configured that way you can do:
# nix develop . --impure
poetry run jupyter notebook
# Copy the url including the token
# Press <Ctrl-A> -> <Ctrl-D> to detatch your screen session
#+end_src

*** Step 2: Tunnel the port to your local computer
Then open a tunnel to your jupyter notebook instance from the local computer.
#+begin_src shell
screen -d -S tunnel -m 'ssh -L 8888:localhost:8888 $USER@moby -N'
#+end_src

On your local computer, go yo the URL copied on step 1.

If moby is restarted you must repeat step 1 (we can try to automate it too).
If your local computer is restarted you need to repeat step 2.
*** VS Code
Tested on versions before 1.88.

1. Install Remote Development Extension
2.

*** Emacs
I use emacs for most things, so it is already installed in moby.
1. Set up your packages of interest ([[https://github.com/doomemacs/doomemacs][doom emacs]] makes things easier). Make sure to include the direnv module.
2.Run
#+begin_src shell
ssh $user@moby -t 'emacsclient -t'

#+end_src
3. You may need to fiddle a bit to get the proper environment working, this is work in progress.

* Papers
This may help you get more context
** Morphological profiling
- What is cell painting
- The main dataset we will work on [cite:@chandrasekaranJUMPCellPainting2023].
- Review on ML on morphological profiles [cite:@chandrasekaranImagebasedProfilingDrug2021a].
** Statistics
- How do we calculate reproducibility in Cell Painting experiments? [cite:@kalininVersatileInformationRetrieval2024]
** Intepretable Deep Learning
*** Counterfactuals
- The basis of our plan. A new preprint will be released soon. [cite:@ecksteinDiscriminativeAttributionCounterfactuals2021]
*** Generative modelling
- Recent work in the interface of morphological profiling and Generative Deep Learning [cite:@lamiableRevealingInvisibleCell2023]
* Selected important events
- <2024-07-02 Tue> Alán's presentation with Janelia folks for a potential collaboration on Counterfactuals (See [[*Counterfactuals][Counterfactuals]]).
- ~<2024-07-26 Fri>  Mock Hackathon alongside CytoData to iron-out the issues and details necessary before the actual hackathon.
- <2024-09-17 Tue> Hackathon organised by Alán, as part of SBI2-CytoData.
