#+title: Interpretable Cells Project
#+bibliography: local-bib.bib
#+cite_export: csl

General resources and how-to's for logistics and our technologies.
* Project
** Overview
We plan to use generative Deep Learning tools to
** Plan
*** Data acquisition
- Selecting which data to acquire
  - Working with all compounds is tricky as not all compounds has been tested in all sources which may induce bias:
    - First idea would be to impose filters: at least 3 sources, 2 wells etc.. while removing the minimum amount of compounds.
    - We could do the same, but instead of removing the minimum amount of compounds, keeping just compounds with a huge amount of samples
      Obviously most of compounds has a low amount of samples so this conditions would greatly limit the amount of different compounds but might end up
      in more samples for later cladssification.
    - Last idea is to use the *Target2 Dataset*
      - Either using the Target2 plate: each compounds always at the same well.
      - Either using a enrich version, using compound from Target2 but not necessarily the Target2 plate only resulting in compounds having been tested sometimes
        more than others but at least in different wells.
  - Find which compounds/genes of JUMP have an associated MoA
*** Select subset of JUMP data to use as a proxy
- It might be recquired to crop the image around each nuclei.
*** Pick, implement and train a generative architecture of a CNN
- Input:
  - Option A: A given compound
  - Option B: A vector in the embedding space
- Output:
*** Select a classifier from other projects in the lab
- X = compound (Adit's classifier)

*** Benchmark
There are multiple options.
- MoAs
- Knowledge graph (see with John)
- Research other potential benchmarks

* Resources
* Server (moby)
Follow [[https://github.com/broadinstitute/monorepo/tree/2d3fc5a14e3eabe8a2bd7ce6b124a2c11825df5d/management/servers/onboarding.org][these]] instructions to set up access to the server.
* Papers
This may help you get more context
** Morphological profiling
- What is cell painting
- The main dataset we will work on [cite:@chandrasekaranJUMPCellPainting2023].
- Review on ML on morphological profiles [cite:@chandrasekaranImagebasedProfilingDrug2021a].
** Statistics
- How do we calculate reproducibility in Cell Painting experiments? [cite:@kalininVersatileInformationRetrieval2024]
** Intepretable Deep Learning
*** Counterfactuals
- The basis of our plan. A new preprint will be released soon. [cite:@ecksteinDiscriminativeAttributionCounterfactuals2021]
*** Generative modelling
- Recent work in the interface of morphological profiling and Generative Deep Learning [cite:@lamiableRevealingInvisibleCell2023]

** CycleGans and Generative Networks
[cite:@zhuUnpairedImageToImageTranslation2017]

* Learning tools
- git basics: [[https://ohmygit.org/][oh my git]]
* Selected important events
- <2024-07-09 Tue> Alán's presentation with Janelia folks for a potential collaboration on Counterfactuals (See [[*Counterfactuals][Counterfactuals]]).
- ~<2024-07-26 Fri> TBC: Mock Hackathon alongside CytoData to iron-out the issues and details necessary before the actual hackathon.
- <2024-09-17 Tue> Hackathon organised by Alán, as part of SBI2-CytoData.

* Bibliography
#+print_bibliography:
